### ISSUE TITLE
Update peerDependencies in package.json

### ISSUE THREAD

**Issue by RandScullard** [megazazik/react-cached-callback#16]
I would like to use react-cached-callback in a React 17 project. When I do `npm install` I get a "Conflicting peer dependency" error. In react-cached-callback's package.json, peerDependencies is currently:

```
  "peerDependencies": {
    "react": "^16.8.0"
  },
```

If react-cached-callback is compatible with React 17 (and possibly even React 18), it would be very helpful if the peerDependencies could be updated to reflect this.

**Comment by megazazik** [comment]
Hi, @RandScullard. I have added react 17 and 8 to peerDependencies and published `react-cached-callback@2.0.4`.
